source "https://rubygems.org"

gem "fluentd", "1.4.2"
gem "oj", "3.5.1"
gem "fluent-plugin-multi-format-parser", "~> 1.0.0"
gem "fluent-plugin-concat", "~> 2.3.0"
gem "fluent-plugin-grok-parser", "~> 2.5.0"
gem "fluent-plugin-prometheus", "~> 1.3.0"
gem "fluent-plugin-rewrite-tag-filter", "~> 2.1.0"
gem "fluent-plugin-splunk-hec", "1.1.0"
gem "fluent-plugin-kubernetes_metadata_filter", "~> 2.1.4"
gem "fluent-plugin-systemd", "~> 1.0.1"
gem "fluent-plugin-s3", "~> 1.1.6"
gem "aws-sdk-s3", "~> 1.0"
gem "ffi"
